### ISSUE TITLE
Переход с всплывающих окошек к сообщению.

### ISSUE THREAD

**Issue by Darca** [highway-accident/tracker#3]
Выдает "Сообщение от пользователя <a href="/app.php/users/5/show" class="uploader">Darca</a>"
По адрему app.php/im/1/show

**Comment by highway-accident** [comment]
Ээ.. не понял проблемы. От кого и кому сообщение, и что не так?

**Comment by highway-accident** [comment]
Запретил отправку сообщений самому себе.
